Create table usuarios (
ID Int UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
login Varchar(30),
senha Varchar(40),
empresa Varchar(40),
cnpj Varchar(40),
ramo Varchar(40),
solicitante Varchar(40),
telefone Varchar(40),
email Varchar(40),
endereco Varchar(40),
bairro Varchar(40),
cidade Varchar(40),
ref Varchar(40),
Primary Key (ID)) ENGINE = MyISAM;                                                                                                                                                                                                